apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.environment }}-service
  namespace: {{ .Values.namespace}}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.environment }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 3000
  type: {{ .Values.service.type }}